### ISSUE TITLE
Connect all Send Buttons to a database  

### ISSUE THREAD

**Issue by weebo-ary** [dsclnct/DSC-Website#1]
We are using Firebase  Storage / Mongo Database for managing the database. Code the script and make it enable to store the messages in the database.

**Comment by bresha** [comment]
I'm interesting in working on this issue and I guess that you need messages sent to you stored in firebase, is that correct? I checked firebase documentation and firebase requires some setup using npm and webpack/Rollup to make it possible to work with it. Do you plan to use webpack?

**Comment by bresha** [comment]
I checked documentation again and I see it can be used with script tag, do you want it to be done that way?
