### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by weebo-ary** [dsclnct/DSC-Website#2]
We have to add some  `meta` tags and other related stuffs for ranking our site in different Search Engines

**Comment by gantavyamalviya** [comment]
Hey @weebo-ary 
Can you assign this to me.
Will add all the necessary meta tags, to rank up the website.

**Comment by awantika10** [comment]
> Hey @weebo-ary
> Can you assign this to me.
> Will add all the necessary meta tags, to rank up the website.

Sure!
